### ISSUE TITLE
Windows Error

### ISSUE THREAD

**Issue by psycik** [adafruit/Adafruit_nRF52_nrfutil#32]
nrf_dfu_* always changes but the error is the same. Tried multiple versions with no luck. How am I supposed to flash if this does not work?

```
adafruit-nrfutil --verbose dfu serial --package C:\Users\psyc\Desktop\feather_nrf52832_bootloader-0.6.1.zip -p COM5 -b 115200 --singlebank --touch 1200
Traceback (most recent call last):
  File "C:\Users\psyc\AppData\Roaming\Python\Python38\Scripts\adafruit-nrfutil-script.py", line 11, in <module>
    load_entry_point('adafruit-nrfutil==0.5.3.post16', 'console_scripts', 'adafruit-nrfutil')()
  File "C:\Users\psyc\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\psyc\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\psyc\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\psyc\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\psyc\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\psyc\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\psyc\AppData\Roaming\Python\Python38\site-packages\nordicsemi\__main__.py", line 290, in serial
    dfu = Dfu(package, dfu_transport=serial_backend)
  File "C:\Users\psyc\AppData\Roaming\Python\Python38\site-packages\nordicsemi\dfu\dfu.py", line 66, in __init__
    self.manifest = Package.unpack_package(self.zip_file_path, self.unpacked_zip_path)
  File "C:\Users\psyc\AppData\Roaming\Python\Python38\site-packages\nordicsemi\dfu\package.py", line 364, in unpack_package
    with open(os.path.join(target_dir, Package.MANIFEST_FILENAME), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\psyc\\AppData\\Local\\Temp\\nrf_dfu_1ivzt9ks\\unpacked_zip\\manifest.json'
```

**Comment by hathach** [comment]
post16 is not latest, it is bundled using python 3.9, you either have to upgrade your python to 3.9 or try post17 https://github.com/adafruit/Adafruit_nRF52_nrfutil/releases/tag/0.5.3.post17

**Comment by psycik** [comment]
adafruit-nrfutil--0.5.3.post17-win.zip still reports version 0.5.3.post16 which does not work either.

**Comment by psycik** [comment]
And problems still remains after upgrading to Python 3.9.6

**Comment by hathach** [comment]
Since IDE worked, it is probably your set up or execution issue. Please double check the parameter etc.. for dfu you can hold the DFU pin to ground when reset.

**Comment by paxswill** [comment]
@psycik I had a similar issue (on Linux), but tracked it down. Newer firmware releases need to be unpacked first, then the newly extracted zip file needs to be used.
